delete_message = false
blacklist = ["asshole", "asshat", "bastard", "bitch", "blowjob", "bollock", "bollocks", "boner", "clitoris", "dumbass", "faggot", "fck", "fuck", "fucking", "fvck", "genital", "jackass", "jizz", "masturbate", "nigga", "nigger", "penis", "pubic", "pussy", "scrotum", "sexual", "sexy", "shit", "shyte", "slut", "smartass", "titties", "titty", "vagina", "whore", "wiseass"]
repeat_char_for_length_of_word = false
custom_char = true
replace_with = "*"
#Range: 1 ~ 100
repeat_char = 3

