<recipetype:create:deploying>.addRecipe(
  "short_scope_deploying",
  <item:createdeco:industrial_iron_sheet>,
  <item:createdeco:industrial_iron_nugget>,
  [
    <item:cgm:short_scope>
  ],
  false
);
