<recipetype:minecraft:crafting>.addShaped(
  "bell_shaped_crafting",
  <item:minecraft:bell>,
  [
    [<item:minecraft:stick>,<item:minecraft:stick>,<item:minecraft:stick>],
    [<item:minecraft:air>,<item:create:brass_sheet>,<item:minecraft:air>],
    [<item:create:brass_sheet>,<item:create:brass_nugget>,<item:create:brass_sheet>]
  ]
);
