<recipetype:create:compacting>.addRecipe(
  "blaze_cake_base_compacting",
  <constant:create:heat_condition:none>,
  [
    <item:create:blaze_cake_base>
  ],
  [
    <item:create:dough>,
    <item:minecraft:sugar>,
    <item:create:cinder_flour>
  ],
  [],
  100
);
